let shopItemsData = [
    {
      id:"BRM01",
      productName:"Brown Bread Flour",
      price:350,
      desc:"Free Brown Bread Flour-1kg",
     img:"../images/shop/brown-bread-flour.svg",
    },
    {
      id:"BRM02",
      productName:"Pasta",
      price: 350,
      desc:"Wheat Pasta-500gm",
      img:"../images/shop/img-1.svg",
    },
    {
      id:"BRM03",
      productName:"Vegan Corn Flour",
      price:150,
      desc:"Vegan Corn flour-500gm",
      img:"../images/shop/img-2.svg",
    },
    {
      id:"BRM04",
      productName:"Spelt Flakes",
      price:50,
      desc:"Rinature Organic Spelt Flakes-500gm",
      img:"../images/shop/img-3.svg",
    },
    {
      id:"BRM05",
      productName:"Organic Walnuts",
      price:750,
      desc:"Organic Raw Sprouted Walnuts-1kg",
      img:"../images/shop/img-4.svg",
    },
    {
      id:"BRM06",
    productName:"Pistachios",
    price:256,
      desc:"California Roasted Tasty & Healthy Pista-200gm",
     img:"../images/shop/img-5.svg",
    },
       {
          id:"BRM07",
         productName:"pasta",
         price:750,
         desc:"Wheat Pasta-1kg",
          img:"../images/shop/img-1.svg",
        },
        {
          id:"BRM08",
         productName:"Cookies",
          price:300,
          desc:"Brown Flour Cookies-1kg",
        img:"../images/shop/img-6.svg",    
          },
         {
          id:"BRM09",
          productName:"Cacao Powder",
          price:150,
          desc:"Organic Raw Cacao Powder-250gm",
         img:"../images/shop/img-7.svg",
        },
        {
          id:"BRM10",
          productName:"Cinnamon Powder",
          price:550,
         desc:"Organic Ceylon Cinnamon Powder-100gm",
          img:"../images/shop/img-8.svg",
      },
       {
         id:"BRM11",      
          productName:"Chat Masala",
          price:89,
          desc:"100% Pure and Natural Chat Masala-90gm",
         img:"../images/shop/img-9.svg",
       },    
        {
          id:"BRM12",
          productName:"Red Chilli Flakes",
         price:80,
          desc:"Red Chilli Flakes-100gm",
         img:"../images/shop/img-10.svg",
       },
      {
         id:"BRM13",
          productName:"Red Chilli Powder",
          price:350,       
          desc:"Organin and Smoky Red chilli powder",        
          img:"../images/shop/img-11.svg",
     },
       {
        id:"BRM14",
         productName:"Brown Basmati Rice",
          price:550,
          desc:"Organic Brown basmati rice-1kg",
        img:"../images/shop/img-12.svg",
        },
        {
          id:"BRM15",
          productName:"Rummo Pasta",
          price:350,
          desc:"Rummo Pasta-1kg",
        img:"../images/shop/img-13.svg",
        },
       {
          id:"BRM16",
          productName:"Dalia",
          price:31,
          desc:"Organic & healthy dalia(broken-wheat)-500gm",
          img:"../images/shop/img-14.svg",
       },
       {
         id:"BRM17",
          productName:"Chocos",
          price:150,
          desc:"Nesqucik Chocos high in calcium & protein,vitamin,iron,etc.",
          img:"../images/shop/img-15.svg",
        },
        {
          id:"BRM18",
          productName:"cereal",
          price:316,
          desc:"Legumi_cannellini multigrain cereal & fruits-300gm",
          img:"../images/shop/img-16.svg" ,
        },
        {
          id:"BRM19",
          productName:"Chocolate-ereals",
          price: 450,
          desc:"Nestle-Nesqucik chocolate-ereals-375gm",
          img:"../images/shop/img-17.svg",
        },
        {
          id:"BRM20",
          productName:"White Flour",
          price:250,
          desc:"Doves farm organic plain white Flour-1kg",
          img:"../images/shop/img-18.svg",
        },
        {
          id:"BRM21",
          productName:"Pasta",
          price:350,
          desc:"Biona italian wholegrain pasta-500gm",
          img:"../images/shop/img-19.svg",
        },
        {
          id:"BRM22",
          productName:"Cereal bar",
          price: 150,
          desc:"Cereal bar with tahini & Cacao-60gm",
          img:"../images/shop/img-20.svg",
        },
         {
          id:"BRM23",
          productName:"Chickpeas",
          price:750,
          desc:"Organic chickpeas-1kg",
          img:"../images/shop/img-21.svg",
        },
        {
          id:"BRM24",
          productName:"Dal Chini",
          price:74,
          desc:"organic Cinnamon(Dal chini)-100gm",
          img:"../images/shop/img-22.svg",
        },
     ];